version: '3.8'

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./app
    ports:
      - 8383:8383
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432